import { defineStore } from 'pinia'
import { ref, computed, watch } from 'vue'
import _ from 'lodash'
import { Peer } from "peerjs"
import { useQuasar, copyToClipboard } from 'quasar'

export const useIcons = defineStore('icons', () => {

  const $q = useQuasar()

  const _icons = [ "search", "home", "account_circle", "settings", "done", "info", "check_circle", "delete", "visibility", "shopping_cart",
  "favorite", "description", "logout", "favorite_border", "lock", "schedule", "language", "help_outline", "face", "manage_accounts",
  "verified", "filter_alt", "thumb_up", "event", "fingerprint", "dashboard", "list", "login", "visibility_off", "check_circle_outline",
  "calendar_today", "highlight_off", "help", "paid", "task_alt", "question_answer", "date_range", "article", "open_in_new", "shopping_bag",
  "lightbulb", "perm_identity", "credit_card", "history", "trending_up", "account_balance", "delete_outline", "report_problem", "fact_check", "assignment",
  "verified_user", "star_rate", "arrow_right_alt", "account_balance_wallet", "autorenew", "build", "view_list", "print", "work", "store",
  "analytics", "today", "delete_forever", "admin_panel_settings", "calendar_month", "lock_open", "watch_later", "grade", "room", "savings",
  "update", "code", "receipt", "add_shopping_cart", "contact_support", "power_settings_new", "pets", "done_all", "explore", "bookmark",
  "note_add", "account_box", "reorder", "bookmark_border", "pending_actions", "shopping_basket", "payment", "launch", "drag_indicator", "supervisor_account",
  "touch_app", "pending", "zoom_in", "assessment", "leaderboard", "thumb_up_off_alt", "open_in_full", "preview", "exit_to_app", "done_outline",
  "assignment_ind", "published_with_changes", "card_giftcard", "view_in_ar", "feedback", "work_outline", "timeline", "swap_horiz", "dns", "assignment_turned_in",
  "sync_alt", "stars", "flight_takeoff", "label", "tips_and_updates", "book", "contact_page", "bug_report", "space_dashboard", "alarm",
  "cached", "translate", "pan_tool", "gavel", "edit_calendar", "supervised_user_circle", "minimize", "extension", "android", "accessibility",
  "get_app", "rocket_launch", "record_voice_over", "add_task", "trending_flat", "question_mark", "hourglass_empty", "help_center", "accessibility_new", "rule",
  "thumb_down", "sticky_note_2", "source", "settings_applications", "dashboard_customize", "find_in_page", "support", "flutter_dash", "ads_click", "close_fullscreen",
  "redeem", "announcement", "loyalty", "swap_vert", "view_headline", "arrow_circle_right", "restore", "dangerous", "euro_symbol", "group_work",
  "sensors", "compare_arrows", "subject", "table_view", "disabled_by_default", "nightlight_round", "privacy_tip", "https", "toc", "arrow_circle_up",
  "track_changes", "copyright", "bookmarks", "grading", "api", "input", "query_builder", "perm_media", "view_module", "build_circle",
  "currency_exchange", "zoom_out", "perm_contact_calendar", "backup", "open_with", "settings_phone", "circle_notifications", "book_online", "speaker_notes", "perm_phone_msg",
  "wysiwyg", "label_important", "card_membership", "arrow_circle_down", "file_present", "pageview", "3d_rotation", "upgrade", "integration_instructions", "change_history",
  "trending_down", "swipe", "class", "accessible", "g_translate", "settings_accessibility", "percent", "expand", "offline_bolt", "production_quantity_limits",
  "settings_backup_restore", "arrow_circle_left", "aspect_ratio", "model_training", "donut_large", "view_column", "segment", "calendar_view_month", "schedule_send", "alarm_on",
  "maximize", "bookmark_add", "thumbs_up_down", "settings_ethernet", "theaters", "view_agenda", "thumb_down_off_alt", "important_devices", "unpublished", "invert_colors",
  "open_in_browser", "opacity", "commute", "addchart", "no_accounts", "history_toggle_off", "system_update_alt", "view_week", "youtube_searched_for", "tour",
  "hide_source", "bookmark_added", "turned_in", "mark_as_unread", "plagiarism", "shop", "settings_input_antenna", "search_off", "not_started", "flight_land",
  "shopping_cart_checkout", "assignment_late", "donut_small", "contactless", "saved_search", "highlight_alt", "assignment_return", "settings_input_component", "view_carousel", "anchor",
  "hotel_class", "view_quilt", "balance", "filter_alt_off", "turned_in_not", "all_inbox", "mediation", "settings_remote", "edit_off", "fit_screen",
  "hourglass_full", "flaky", "toll", "remove_shopping_cart", "lock_clock", "rocket", "settings_voice", "swap_horizontal_circle", "view_sidebar", "online_prediction",
  "event_seat", "vertical_split", "next_plan", "pregnant_woman", "data_exploration", "restore_from_trash", "camera_enhance", "markunread_mailbox", "terminal", "dynamic_form",
  "tab", "lock_reset", "calendar_view_week", "view_stream", "accessible_forward", "request_page", "token", "remove_done", "add_to_drive", "settings_power",
  "smart_button", "card_travel", "outbox", "try", "offline_pin", "calendar_view_day", "find_replace", "rowing", "chrome_reader_mode", "compress",
  "outlet", "assignment_returned", "settings_brightness", "fax", "http", "density_medium", "alarm_add", "new_label", "backup_table", "spellcheck",
  "generating_tokens", "restore_page", "credit_card_off", "play_for_work", "wifi_protected_setup", "add_card", "free_cancellation", "settings_overscan", "gif", "outbound",
  "swap_vertical_circle", "quickreply", "settings_input_composite", "disabled_visible", "cancel_schedule_send", "view_day", "123", "comment_bank", "work_history", "switch_access_shortcut",
  "line_weight", "assured_workload", "view_timeline", "event_repeat", "horizontal_split", "polymer", "display_settings", "batch_prediction", "send_and_archive", "picture_in_picture",
  "satellite_alt", "webhook", "pan_tool_alt", "code_off", "bookmark_remove", "noise_control_off", "settings_bluetooth", "manage_history", "shop_two", "flip_to_front",
  "html", "gif_box", "output", "speaker_notes_off", "eject", "alarm_off", "perm_data_setting", "settings_input_hdmi", "perm_scan_wifi", "hourglass_disabled",
  "settings_cell", "app_blocking", "switch_access_shortcut_add", "sensors_off", "work_off", "picture_in_picture_alt", "line_style", "perm_device_information", "troubleshoot", "subtitles_off",
  "update_disabled", "join_full", "javascript", "app_shortcut", "voice_over_off", "swipe_left", "abc", "private_connectivity", "settings_input_svideo", "lightbulb_circle",
  "flip_to_back", "view_array", "open_in_new_off", "swipe_right", "install_desktop", "join_inner", "all_out", "swipe_up", "shop_2", "label_off",
  "tab_unselected", "rounded_corner", "density_small", "text_rotate_vertical", "data_thresholding", "explore_off", "commit", "text_rotation_none", "install_mobile", "not_accessible",
  "view_kanban", "arrow_outward", "pin_invoke", "css", "swipe_down", "join_left", "extension_off", "perm_camera_mic", "pinch", "lock_person",
  "spatial_audio_off", "swipe_vertical", "pin_end", "noise_aware", "view_cozy", "join_right", "text_rotate_up", "swipe_right_alt", "text_rotation_angleup", "text_rotation_down",
  "text_rotation_angledown", "browse_gallery", "php", "view_comfy_alt", "view_compact_alt", "swipe_down_alt", "network_ping", "density_large", "on_device_training", "add_home",
  "swipe_left_alt", "swipe_up_alt", "spatial_tracking", "unfold_more_double", "spatial_audio", "width_full", "unfold_less_double", "repartition", "width_normal", "width_wide",
  "transcribe", "hls", "hls_off", "face_unlock", "close", "menu", "expand_more", "arrow_back", "chevron_right", "arrow_forward_ios",
  "arrow_back_ios", "cancel", "arrow_drop_down", "more_vert", "arrow_forward", "chevron_left", "check", "expand_less", "more_horiz", "refresh",
  "apps", "payments", "arrow_upward", "east", "campaign", "arrow_back_ios_new", "arrow_downward", "arrow_right", "menu_open", "fullscreen",
  "arrow_drop_up", "unfold_more", "double_arrow", "maps_home_work", "west", "expand_circle_down", "south", "arrow_left", "north_east", "north",
  "home_work", "first_page", "fullscreen_exit", "arrow_drop_down_circle", "last_page", "unfold_less", "subdirectory_arrow_right", "legend_toggle", "south_east", "app_settings_alt",
  "assistant_direction", "subdirectory_arrow_left", "north_west", "waterfall_chart", "switch_left", "south_west", "pivot_table_chart", "switch_right", "apps_outage", "offline_share",
  "add_home_work", "person", "notifications", "groups", "people", "share", "person_outline", "school", "person_add", "public",
  "emoji_events", "group", "notifications_active", "engineering", "construction", "people_alt", "group_add", "psychology", "health_and_safety", "travel_explore",
  "thumb_up_alt", "water_drop", "notifications_none", "emoji_emotions", "sports_esports", "location_city", "ios_share", "sentiment_very_satisfied", "sentiment_satisfied", "precision_manufacturing",
  "person_add_alt", "emoji_objects", "military_tech", "science", "workspace_premium", "history_edu", "cake", "sentiment_dissatisfied", "sentiment_very_dissatisfied", "handshake",
  "coronavirus", "emoji_people", "self_improvement", "person_remove", "poll", "whatshot", "sports_soccer", "domain", "mood", "recommend",
  "people_outline", "female", "person_off", "recycling", "male", "person_add_alt_1", "connect_without_contact", "sentiment_neutral", "back_hand", "hiking",
  "masks", "architecture", "waving_hand", "notifications_off", "thumb_down_alt", "luggage", "real_estate_agent", "front_hand", "mood_bad", "vaccines",
  "emoji_nature", "switch_account", "nights_stay", "catching_pokemon", "king_bed", "interests", "compost", "sports_basketball", "notification_add", "sports_kabaddi",
  "sports", "emoji_symbols", "reduce_capacity", "emoji_food_beverage", "sick", "man", "diversity_3", "cruelty_free", "emoji_transportation", "sports_tennis",
  "cookie", "heart_broken", "transgender", "elderly", "outdoor_grill", "add_moderator", "deck", "woman", "social_distance", "add_reaction",
  "follow_the_signs", "personal_injury", "plus_one", "fireplace", "clean_hands", "piano", "scale", "sanitizer", "wallet", "surfing",
  "pix", "sports_motorsports", "sports_handball", "sports_baseball", "edit_notifications", "diversity_1", "hive", "sports_volleyball", "pages", "sports_football",
  "downhill_skiing", "kayaking", "public_off", "groups_2", "single_bed", "remove_moderator", "skateboarding", "group_remove", "notifications_paused", "co2",
  "person_remove_alt_1", "boy", "safety_divider", "psychology_alt", "fitbit", "domain_add", "sports_cricket", "diversity_2", "group_off", "sports_mma",
  "nordic_walking", "sports_golf", "sports_martial_arts", "girl", "paragliding", "6_ft_apart", "party_mode", "snowboarding", "thunderstorm", "kitesurfing",
  "sports_gymnastics", "snowshoeing", "groups_3", "sports_hockey", "ice_skating", "sports_rugby", "face_6", "south_america", "elderly_woman", "sledding",
  "face_3", "scoreboard", "person_2", "face_2", "sign_language", "face_4", "no_luggage", "cyclone", "piano_off", "person_4",
  "face_5", "flood", "scuba_diving", "person_3", "severe_cold", "tsunami", "roller_skating", "tornado", "landslide", "volcano",
  "assist_walker", "woman_2", "man_2", "18_up_rating", "blind", "no_adult_content", "man_4", "man_3", "add", "add_circle_outline",
  "content_copy", "add_circle", "send", "clear", "save", "mail", "link", "remove", "filter_list", "inventory_2",
  "inventory", "insights", "remove_circle_outline", "sort", "bolt", "flag", "reply", "add_box", "remove_circle", "push_pin",
  "block", "calculate", "create", "undo", "how_to_reg", "content_paste", "report", "file_copy", "backspace", "shield",
  "archive", "save_alt", "policy", "tag", "change_circle", "redo", "forward", "content_cut", "outlined_flag", "inbox",
  "link_off", "drafts", "ballot", "biotech", "report_gmailerrorred", "delete_sweep", "stacked_bar_chart", "markunread", "square_foot", "add_link",
  "stream", "where_to_vote", "copy_all", "dynamic_feed", "move_to_inbox", "waves", "unarchive", "reply_all", "content_paste_search", "select_all",
  "low_priority", "text_format", "font_download", "save_as", "weekend", "how_to_vote", "upcoming", "gesture", "attribution", "flag_circle",
  "content_paste_go", "next_week", "filter_list_off", "content_paste_off", "report_off", "web_stories", "deselect", "font_download_off", "edit", "navigate_next",
  "photo_camera", "image", "tune", "picture_as_pdf", "receipt_long", "circle", "timer", "auto_stories", "collections", "navigate_before",
  "add_a_photo", "auto_awesome", "palette", "remove_red_eye", "music_note", "add_photo_alternate", "wb_sunny", "brush", "euro", "flash_on",
  "looks_one", "control_point", "auto_fix_high", "style", "adjust", "straighten", "photo_library", "camera", "portrait", "camera_alt",
  "audiotrack", "video_camera_front", "rotate_right", "color_lens", "grid_on", "crop_free", "timelapse", "landscape", "slideshow", "collections_bookmark",
  "currency_rupee", "crop_square", "panorama_fish_eye", "lens", "looks_two", "filter_vintage", "compare", "filter_drama", "looks_3", "image_search",
  "healing", "auto_awesome_motion", "rotate_left", "center_focus_strong", "crop", "blur_on", "wb_incandescent", "flare", "face_retouching_natural", "wb_cloudy",
  "broken_image", "cases", "assistant", "colorize", "filter_none", "brightness_4", "filter_center_focus", "crop_original", "dehaze", "auto_fix_normal",
  "nature_people", "photo", "flash_off", "auto_awesome_mosaic", "tag_faces", "brightness_6", "brightness_5", "details", "grain", "flip_camera_android",
  "brightness_1", "flip", "loupe", "flip_camera_ios", "image_not_supported", "view_comfy", "filter_1", "movie_creation", "add_to_photos", "panorama",
  "animation", "bedtime", "center_focus_weak", "looks_4", "movie_filter", "crop_din", "control_point_duplicate", "filter", "brightness_7", "leak_add",
  "nature", "currency_bitcoin", "incomplete_circle", "texture", "timer_off", "view_compact", "photo_size_select_actual", "video_camera_back", "transform", "motion_photos_on",
  "photo_camera_front", "currency_yen", "rotate_90_degrees_ccw", "mic_external_on", "looks_5", "gradient", "assistant_photo", "wb_twilight", "currency_pound", "contrast",
  "hide_image", "music_off", "exposure_plus_1", "thermostat_auto", "crop_16_9", "shutter_speed", "exposure", "filter_2", "photo_album", "filter_tilt_shift",
  "hdr_strong", "vrpano", "looks", "linked_camera", "brightness_3", "blur_circular", "looks_6", "flash_auto", "motion_photos_auto", "crop_portrait",
  "brightness_2", "iso", "tonality", "photo_filter", "photo_size_select_small", "filter_hdr", "crop_7_5", "rotate_90_degrees_cw", "crop_rotate", "photo_size_select_large",
  "filter_3", "exposure_zero", "hdr_weak", "camera_front", "currency_ruble", "crop_5_4", "filter_frames", "burst_mode", "camera_roll", "logo_dev",
  "filter_b_and_w", "blur_linear", "crop_3_2", "crop_landscape", "switch_camera", "switch_video", "filter_7", "filter_9_plus", "filter_4", "exposure_plus_2",
  "grid_off", "wb_iridescent", "motion_photos_paused", "monochrome_photos", "photo_camera_back", "filter_5", "face_retouching_off", "auto_fix_off", "exposure_neg_1", "panorama_photosphere",
  "leak_remove", "filter_8", "filter_9", "video_stable", "timer_10", "wb_shade", "filter_6", "motion_photos_off", "blur_off", "raw_on",
  "hdr_on", "motion_photos_pause", "vignette", "panorama_horizontal", "dirty_lens", "image_aspect_ratio", "30fps_select", "deblur", "camera_rear", "60fps_select",
  "timer_3", "panorama_wide_angle_select", "24mp", "exposure_neg_2", "currency_yuan", "currency_lira", "autofps_select", "panorama_horizontal_select", "panorama_photosphere_select", "hdr_plus",
  "panorama_wide_angle", "wb_auto", "panorama_vertical_select", "mic_external_off", "panorama_vertical", "12mp", "hdr_enhanced_select", "mp", "hevc", "currency_franc",
  "18mp", "23mp", "raw_off", "10mp", "hdr_off", "bedtime_off", "11mp", "20mp", "3mp", "13mp",
  "16mp", "5mp", "17mp", "21mp", "2mp", "15mp", "14mp", "22mp", "19mp", "4mp",
  "8mp", "7mp", "9mp", "6mp", "email", "location_on", "call", "phone", "business", "chat",
  "mail_outline", "list_alt", "qr_code_scanner", "vpn_key", "chat_bubble_outline", "alternate_email", "forum", "chat_bubble", "textsms", "contact_mail",
  "person_search", "qr_code", "sentiment_satisfied_alt", "qr_code_2", "message", "contacts", "comment", "key", "import_contacts", "app_registration",
  "contact_phone", "import_export", "live_help", "forward_to_inbox", "hourglass_bottom", "hourglass_top", "rss_feed", "mark_email_read", "hub", "read_more",
  "document_scanner", "more_time", "mark_email_unread", "call_end", "clear_all", "dialpad", "phone_enabled", "mark_chat_unread", "cancel_presentation", "3p",
  "call_made", "screen_share", "call_split", "unsubscribe", "present_to_all", "domain_verification", "mark_chat_read", "add_ic_call", "phonelink_ring", "stay_current_portrait",
  "co_present", "call_received", "phonelink_lock", "phone_disabled", "ring_volume", "duo", "phonelink_setup", "location_off", "stay_primary_portrait", "cell_tower",
  "swap_calls", "voicemail", "call_merge", "mobile_screen_share", "phonelink_erase", "person_add_disabled", "domain_disabled", "call_missed_outgoing", "speaker_phone", "cell_wifi",
  "spoke", "desktop_access_disabled", "stop_screen_share", "print_disabled", "call_missed", "pause_presentation", "mark_unread_chat_alt", "dialer_sip", "invert_colors_off", "comments_disabled",
  "wifi_calling", "rtt", "portable_wifi_off", "contact_emergency", "send_time_extension", "stay_current_landscape", "sip", "nat", "mail_lock", "stay_primary_landscape",
  "no_sim", "key_off", "vpn_key_off", "local_shipping", "place", "menu_book", "local_offer", "badge", "map", "category",
  "restaurant", "directions_car", "local_fire_department", "volunteer_activism", "my_location", "local_mall", "flight", "near_me", "handyman", "directions_run",
  "restaurant_menu", "layers", "medical_services", "lunch_dining", "directions_walk", "local_hospital", "celebration", "local_library", "pin_drop", "park",
  "local_atm", "local_activity", "person_pin", "local_cafe", "design_services", "delivery_dining", "rate_review", "directions_bus", "directions_bike", "local_police",
  "fastfood", "directions_car_filled", "home_repair_service", "zoom_out_map", "hotel", "cleaning_services", "local_phone", "local_grocery_store", "miscellaneous_services", "navigation",
  "local_gas_station", "person_pin_circle", "train", "local_parking", "local_florist", "diamond", "directions", "local_post_office", "money", "two_wheeler",
  "traffic", "add_business", "electrical_services", "factory", "local_bar", "directions_boat", "alt_route", "route", "pedal_bike", "agriculture",
  "beenhere", "360", "liquor", "warehouse", "emergency", "moving", "local_airport", "sailing", "add_location_alt", "local_dining",
  "maps_ugc", "local_taxi", "ramen_dining", "trip_origin", "hail", "local_drink", "local_printshop", "local_laundry_service", "theater_comedy", "directions_bus_filled",
  "local_pizza", "not_listed_location", "add_location", "dinner_dining", "transfer_within_a_station", "bakery_dining", "forest", "terrain", "multiple_stop", "wine_bar",
  "takeout_dining", "store_mall_directory", "icecream", "museum", "nightlife", "local_pharmacy", "add_road", "hardware", "set_meal", "departure_board",
  "local_see", "ev_station", "electric_car", "plumbing", "festival", "car_rental", "layers_clear", "attractions", "edit_location", "local_convenience_store",
  "pest_control", "zoom_in_map", "edit_road", "run_circle", "dry_cleaning", "edit_location_alt", "edit_attributes", "church", "medical_information", "moped",
  "wrong_location", "car_repair", "local_movies", "satellite", "directions_boat_filled", "tram", "taxi_alert", "breakfast_dining", "soup_kitchen", "signpost",
  "atm", "subway", "transit_enterexit", "brunch_dining", "straight", "merge", "electric_bike", "hvac", "directions_transit", "electric_scooter",
  "bus_alert", "crisis_alert", "local_car_wash", "connecting_airports", "egg", "local_hotel", "mode_of_travel", "castle", "stadium", "streetview",
  "directions_subway", "safety_check", "compass_calibration", "mosque", "car_crash", "electric_rickshaw", "airline_stops", "turn_right", "directions_railway", "no_meals",
  "railway_alert", "electric_moped", "fork_right", "local_play", "bike_scooter", "pest_control_rodent", "near_me_disabled", "airlines", "turn_left", "snowmobile",
  "directions_transit_filled", "no_crash", "u_turn_left", "egg_alt", "no_transfer", "directions_subway_filled", "directions_railway_filled", "flight_class", "tire_repair", "temple_buddhist",
  "fort", "kebab_dining", "minor_crash", "sos", "emergency_share", "u_turn_right", "temple_hindu", "synagogue", "fork_left", "turn_sharp_right",
  "remove_road", "roundabout_right", "turn_slight_right", "turn_slight_left", "screen_rotation_alt", "fire_truck", "roundabout_left", "turn_sharp_left", "emergency_recording", "ramp_left",
  "ramp_right", "fire_hydrant_alt", "file_download", "file_upload", "download", "folder", "grid_view", "upload_file", "cloud_upload", "folder_open",
  "text_snippet", "cloud", "request_quote", "cloud_download", "drive_file_rename_outline", "upload", "attachment", "download_for_offline", "newspaper", "create_new_folder",
  "downloading", "folder_shared", "cloud_done", "workspaces", "cloud_queue", "topic", "download_done", "approval", "cloud_off", "drive_file_move",
  "file_open", "drive_folder_upload", "file_download_done", "cloud_sync", "attach_email", "rule_folder", "folder_zip", "cloud_circle", "folder_copy", "snippet_folder",
  "difference", "file_download_off", "folder_delete", "drive_file_move_rtl", "folder_off", "format_overline", "play_arrow", "play_circle_filled", "videocam", "play_circle",
  "mic", "volume_up", "pause", "play_circle_outline", "replay", "volume_off", "skip_next", "library_books", "speed", "fiber_manual_record",
  "stop", "movie", "skip_previous", "new_releases", "playlist_add", "loop", "equalizer", "fast_forward", "web", "video_library",
  "playlist_add_check", "library_add", "mic_off", "pause_circle", "subscriptions", "video_call", "volume_mute", "stop_circle", "repeat", "not_interested",
  "shuffle", "sort_by_alpha", "mic_none", "fast_rewind", "library_music", "videocam_off", "volume_down", "recent_actors", "web_asset", "library_add_check",
  "queue_music", "hearing", "pause_circle_filled", "subtitles", "pause_circle_outline", "fiber_new", "note", "av_timer", "album", "playlist_play",
  "games", "queue", "radio", "replay_circle_filled", "branding_watermark", "forward_10", "replay_10", "closed_caption", "video_settings", "featured_play_list",
  "playlist_add_check_circle", "control_camera", "high_quality", "slow_motion_video", "add_to_queue", "playlist_remove", "airplay", "repeat_one", "call_to_action", "snooze",
  "hd", "closed_caption_off", "repeat_on", "replay_30", "featured_video", "shuffle_on", "5g", "forward_30", "music_video", "playlist_add_circle",
  "queue_play_next", "replay_5", "audio_file", "art_track", "hearing_disabled", "video_file", "interpreter_mode", "forward_5", "explicit", "4k",
  "video_label", "fiber_smart_record", "repeat_one_on", "closed_caption_disabled", "remove_from_queue", "surround_sound", "play_disabled", "web_asset_off", "sd", "missed_video_call",
  "10k", "lyrics", "fiber_pin", "fiber_dvr", "4k_plus", "1k", "2k", "1k_plus", "8k", "9k_plus",
  "5k", "8k_plus", "3k", "5k_plus", "9k", "6k_plus", "2k_plus", "7k", "7k_plus", "3k_plus",
  "6k", "star", "check_box", "check_box_outline_blank", "radio_button_unchecked", "radio_button_checked", "star_border", "toggle_on", "star_outline", "toggle_off",
  "star_half", "indeterminate_check_box", "star_purple500", "star_border_purple500", "warning", "error", "error_outline", "warning_amber", "notification_important", "add_alert",
  "auto_delete", "support_agent", "wifi", "account_tree", "sync", "priority_high", "event_available", "event_note", "confirmation_number", "sms",
  "live_tv", "ondemand_video", "drive_eta", "wifi_off", "event_busy", "do_not_disturb_on", "wc", "more", "power", "do_not_disturb",
  "sync_problem", "time_to_leave", "do_disturb_on", "vpn_lock", "running_with_errors", "folder_special", "enhanced_encryption", "do_disturb", "network_check", "sms_failed",
  "phone_callback", "adb", "system_update", "phone_forwarded", "power_off", "personal_video", "voice_chat", "vibration", "airline_seat_recline_normal", "do_disturb_alt",
  "do_not_disturb_alt", "sync_disabled", "tap_and_play", "no_encryption", "sd_card", "phone_missed", "airline_seat_recline_extra", "imagesearch_roller", "mms", "disc_full",
  "no_encryption_gmailerrorred", "bluetooth_audio", "sd_card_alert", "sync_lock", "sim_card_alert", "do_not_disturb_off", "airline_seat_individual_suite", "phone_paused", "do_disturb_off", "airline_seat_flat",
  "network_locked", "phone_locked", "tv_off", "airline_seat_flat_angled", "phone_bluetooth_speaker", "airline_seat_legroom_normal", "directions_off", "airline_seat_legroom_extra", "airline_seat_legroom_reduced", "video_chat",
  "attach_money", "edit_note", "format_list_bulleted", "mode_edit", "monetization_on", "attach_file", "post_add", "bar_chart", "checklist", "drag_handle",
  "insert_drive_file", "show_chart", "format_quote", "format_list_numbered", "query_stats", "table_chart", "border_color", "pie_chart", "notes", "format_bold",
  "text_fields", "table_rows", "insert_emoticon", "title", "publish", "checklist_rtl", "insert_photo", "auto_graph", "insert_chart_outlined", "mode",
  "draw", "mode_comment", "functions", "insert_link", "insert_invitation", "mode_edit_outline", "format_align_left", "horizontal_rule", "format_italic", "format_color_fill",
  "add_comment", "insert_chart", "linear_scale", "format_size", "stacked_line_chart", "format_underlined", "insert_comment", "bubble_chart", "money_off", "vertical_align_bottom",
  "height", "vertical_align_top", "schema", "format_align_center", "format_paint", "area_chart", "square", "format_color_text", "format_align_right", "scatter_plot",
  "format_list_numbered_rtl", "highlight", "format_align_justify", "merge_type", "data_object", "add_chart", "format_shapes", "numbers", "money_off_csred", "pie_chart_outline",
  "short_text", "format_indent_increase", "strikethrough_s", "vertical_align_center", "format_color_reset", "align_horizontal_left", "move_up", "hexagon", "multiline_chart", "rectangle",
  "score", "move_down", "border_all", "format_indent_decrease", "format_clear", "space_bar", "text_increase", "format_line_spacing", "horizontal_distribute", "polyline",
  "align_vertical_bottom", "candlestick_chart", "align_horizontal_center", "vertical_distribute", "align_horizontal_right", "format_strikethrough", "superscript", "margin", "data_array", "wrap_text",
  "pentagon", "border_clear", "subscript", "align_vertical_top", "align_vertical_center", "border_style", "text_decrease", "padding", "border_outer", "line_axis",
  "insert_page_break", "border_inner", "border_left", "format_textdirection_l_to_r", "border_bottom", "border_vertical", "border_horizontal", "format_textdirection_r_to_l", "border_top", "border_right",
  "shape_line", "type_specimen", "keyboard_arrow_down", "phone_iphone", "smartphone", "keyboard_arrow_right", "computer", "security", "desktop_windows", "smart_display",
  "keyboard_backspace", "phone_android", "keyboard_arrow_up", "laptop", "keyboard_double_arrow_right", "keyboard_arrow_left", "keyboard_return", "smart_toy", "headphones", "keyboard",
  "memory", "point_of_sale", "headset_mic", "tv", "keyboard_double_arrow_left", "mouse", "keyboard_double_arrow_down", "keyboard_voice", "developer_board", "router",
  "videogame_asset", "start", "keyboard_double_arrow_up", "cast_for_education", "device_hub", "headset", "laptop_mac", "cast", "watch", "tablet_mac",
  "devices_other", "desktop_mac", "keyboard_tab", "laptop_chromebook", "phonelink", "monitor", "speaker", "toys", "gamepad", "sim_card",
  "keyboard_alt", "connected_tv", "tablet_android", "cast_connected", "laptop_windows", "device_unknown", "browser_updated", "keyboard_hide", "scanner", "tablet",
  "speaker_group", "keyboard_capslock", "earbuds", "headset_off", "keyboard_command_key", "home_max", "headphones_battery", "smart_screen", "power_input", "dock",
  "browser_not_supported", "earbuds_battery", "phonelink_off", "home_mini", "developer_board_off", "adf_scanner", "videogame_asset_off", "keyboard_control_key", "watch_off", "keyboard_option_key",
  "light_mode", "restart_alt", "dark_mode", "task", "summarize", "password", "sell", "signal_cellular_alt", "devices", "settings_suggest",
  "quiz", "widgets", "storage", "credit_score", "thermostat", "battery_full", "gps_fixed", "price_check", "medication", "pin",
  "gpp_good", "price_change", "battery_charging_full", "tungsten", "fmd_good", "reviews", "air", "note_alt", "bluetooth", "graphic_eq",
  "dvr", "monitor_heart", "nightlight", "sports_score", "access_time", "water", "share_location", "gpp_maybe", "location_searching", "cable",
  "cameraswitch", "shortcut", "airplane_ticket", "wallpaper", "device_thermostat", "radar", "gpp_bad", "data_usage", "monitor_weight", "signal_wifi_4_bar",
  "developer_mode", "mode_night", "wifi_tethering", "battery_std", "discount", "bloodtype", "signal_cellular_4_bar", "fmd_bad", "flashlight_on", "splitscreen",
  "network_wifi", "sim_card_download", "lan", "access_time_filled", "airplanemode_active", "mobile_friendly", "usb", "send_to_mobile", "battery_alert", "screen_search_desktop",
  "lens_blur", "signal_wifi_statusbar_4_bar", "screen_rotation", "signal_wifi_statusbar_connected_no_internet_4", "gps_not_fixed", "system_security_update_good", "bluetooth_connected", "remember_me", "nfc", "pattern",
  "mode_standby", "brightness_high", "battery_saver", "play_lesson", "battery_5_bar", "storm", "data_saver_off", "brightness_medium", "data_saver_on", "brightness_low",
  "signal_wifi_0_bar", "screenshot", "bluetooth_searching", "network_cell", "grid_4x4", "mobiledata_off", "ad_units", "bluetooth_disabled", "hdr_auto", "security_update_good",
  "ssid_chart", "battery_unknown", "battery_4_bar", "wifi_calling_3", "signal_wifi_off", "battery_0_bar", "settings_system_daydream", "signal_wifi_bad", "battery_6_bar", "access_alarms",
  "signal_wifi_connected_no_internet_4", "battery_3_bar", "aod", "access_alarm", "add_to_home_screen", "signal_cellular_0_bar", "flashlight_off", "security_update", "gps_off", "signal_wifi_statusbar_null",
  "sd_storage", "4g_mobiledata", "grid_3x3", "reset_tv", "battery_1_bar", "brightness_auto", "punch_clock", "medication_liquid", "signal_cellular_connected_no_internet_4_bar", "wifi_lock",
  "do_not_disturb_on_total_silence", "nearby_error", "airplanemode_inactive", "1x_mobiledata", "security_update_warning", "signal_cellular_connected_no_internet_0_bar", "battery_2_bar", "screen_lock_portrait", "system_security_update", "wifi_password",
  "screenshot_monitor", "system_security_update_warning", "phishing", "wifi_tethering_off", "edgesensor_high", "dataset", "4g_plus_mobiledata", "signal_cellular_off", "signal_cellular_nodata", "lte_mobiledata",
  "signal_wifi_4_bar_lock", "add_alarm", "bluetooth_drive", "location_disabled", "30fps", "mobile_off", "signal_cellular_null", "media_bluetooth_on", "network_wifi_1_bar", "wifi_find",
  "rsvp", "3g_mobiledata", "grid_goldenratio", "edgesensor_low", "network_wifi_3_bar", "screen_lock_rotation", "usb_off", "60fps", "screen_lock_landscape", "lte_plus_mobiledata",
  "timer_10_select", "signal_cellular_no_sim", "network_wifi_2_bar", "wifi_2_bar", "wifi_tethering_error", "signal_cellular_alt_2_bar", "g_mobiledata", "signal_cellular_alt_1_bar", "timer_3_select", "wifi_1_bar",
  "wifi_channel", "h_mobiledata", "dataset_linked", "media_bluetooth_off", "e_mobiledata", "r_mobiledata", "h_plus_mobiledata", "hdr_on_select", "hdr_auto_select", "nearby_off",
  "hdr_off_select", "devices_fold", "fluorescent", "macro_off", "storefront", "apartment", "fitness_center", "business_center", "spa", "meeting_room",
  "house", "corporate_fare", "ac_unit", "cottage", "family_restroom", "other_houses", "checkroom", "all_inclusive", "grass", "airport_shuttle",
  "child_care", "beach_access", "pool", "kitchen", "casino", "holiday_village", "roofing", "room_service", "room_preferences", "sports_bar",
  "free_breakfast", "bathtub", "escalator_warning", "child_friendly", "foundation", "food_bank", "gite", "villa", "night_shelter", "golf_course",
  "no_photography", "stairs", "microwave", "backpack", "elevator", "smoking_rooms", "wash", "cabin", "house_siding", "hot_tub",
  "countertops", "water_damage", "fire_extinguisher", "charging_station", "carpenter", "rv_hookup", "soap", "baby_changing_station", "smoke_free", "umbrella",
  "tapas", "rice_bowl", "do_not_touch", "tty", "balcony", "no_food", "houseboat", "fence", "bento", "wheelchair_pickup",
  "iron", "bungalow", "chalet", "crib", "do_not_step", "no_meeting_room", "escalator", "dry", "stroller", "no_drinks",
  "no_cell", "no_flash", "no_backpack", "no_stroller", "vaping_rooms", "desk", "vape_free", "manage_search", "feed", "chair",
  "bed", "podcasts", "coffee", "shower", "yard", "window", "door_front", "light", "garage", "dining",
  "flatware", "coffee_maker", "blender", "table_restaurant", "bedroom_parent", "camera_indoor", "bedroom_baby", "bathroom", "chair_alt", "door_sliding",
  "camera_outdoor", "door_back", "living", "doorbell", "bedroom_child", "table_bar", "sensor_door", "electric_bolt", "sensor_window", "energy_savings_leaf",
  "shield_moon", "solar_power", "auto_mode", "oil_barrel", "wind_power", "sensor_occupied", "electric_meter", "heat_pump", "gas_meter", "propane_tank",
  "mode_fan_off", "roller_shades", "propane", "broadcast_on_personal", "roller_shades_closed", "blinds", "curtains", "blinds_closed", "vertical_shades_closed", "broadcast_on_home",
  "curtains_closed", "vertical_shades", "nest_cam_wired_stand" ]

  // Number of icons to display
  var n_icons = 100
  // Filter
  const filter = ref("")


  const icons = computed(() => _icons.filter(i => !filter.value || i.includes(filter.value)).slice(0, n_icons))

  return {
    filter,
    icons
  }
})
